[versions]
coroutines = "1.4.3"

aws-lambda-java-events = "3.8.0"
aws-lambda-java-core = "1.2.1"
aws-lambda-java-log4j2 = "1.2.0"
awssdk = "2.16.43"

jackson = "2.12.3"

tgbotapi = "0.33.3"

log4j = "2.14.1"

junit5 = "5.7.1"
aws-junit5 = "6.0.1"

[libraries]
kotlinx-coroutines-jdk8 = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-jdk8", version.ref = "coroutines" }

aws-lambda-java-events = { group = "com.amazonaws", name = "aws-lambda-java-events", version.ref = "aws-lambda-java-events" }
aws-lambda-java-core = { group = "com.amazonaws", name = "aws-lambda-java-core", version.ref = "aws-lambda-java-core" }
aws-lambda-java-log4j2 = { group = "com.amazonaws", name = "aws-lambda-java-log4j2", version.ref = "aws-lambda-java-log4j2" }
dynamodb = { group = "software.amazon.awssdk", name = "dynamodb", version.ref = "awssdk" }

jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }

tgbotapi-core = { group = "dev.inmo", name = "tgbotapi.core", version.ref = "tgbotapi" }

log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
log4j-slf4j-impl = { group = "org.apache.logging.log4j", name = "log4j-slf4j-impl", version.ref = "log4j" }

junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit5" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }
aws-junit5-dynamo-v2 = { group = "me.madhead.aws-junit5", name = "dynamo-v2", version.ref = "aws-junit5" }

[bundles]
tgbotapi = ["tgbotapi-core"]
log4j = ["log4j-core", "log4j-slf4j-impl"]
aws-lambda = ["aws-lambda-java-events", "aws-lambda-java-core", "aws-lambda-java-log4j2", "jackson-databind"]
